# Use Node.js image
FROM node:16

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the entire frontend app
COPY . .

# Expose the port React will run on
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
